/**
 * PDF Export Utility
 * Exports financial data to PDF format
 */

export interface ExportData {
  title: string;
  data: Record<string, any>;
  generatedAt: Date;
}

export async function exportToPDF(data: ExportData): Promise<Blob> {
  // Using a simple HTML to PDF approach
  const html = generateHTML(data);
  
  // In production, use a library like jsPDF or html2pdf
  const blob = new Blob([html], { type: 'text/html' });
  return blob;
}

function generateHTML(data: ExportData): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${data.title}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { margin-top: 40px; font-size: 12px; color: #666; }
      </style>
    </head>
    <body>
      <h1>${data.title}</h1>
      <p>Generated on: ${data.generatedAt.toLocaleString('en-IN')}</p>
      <table>
        <tbody>
          ${Object.entries(data.data)
            .map(
              ([key, value]) =>
                `<tr><td><strong>${key}</strong></td><td>${JSON.stringify(value)}</td></tr>`
            )
            .join('')}
        </tbody>
      </table>
      <div class="footer">
        <p>This report was generated by FinPilot</p>
      </div>
    </body>
    </html>
  `;
}

export function downloadFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
